name: databricks-cicd
on:
  push:
    branches: [dev, test, main]
  pull_request:
    branches:
      - '*'
jobs:
  main:
    runs-on: ubuntu-latest
    # Name of the environment you created
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Install databricks CLI as per https://docs.databricks.com/dev-tools/cli/databricks-cli.html
      - name: Install databricks CLI
        run: |
         curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      # List the databricks repos within the workspace whose credentials
      # are stored in the Github Environment "my-environment"
      - name: List databricks repos
        env:
          # Note the host is an "environment variable" in the Github Environment
          # while the token is a "secret" in the Github Environment
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks repos list
          
      - name: Upload tests and run jobs
        env:
          # Note the host is an "environment variable" in the Github Environment
          # while the token is a "secret" in the Github Environment
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          # run_tests.sh
          databricks fs cp tests/integration_test.py dbfs:/Workspace/Users/keshavchaudhary940@gmail.com/tests/integration_test.py
          
          databricks jobs run-now --job-id 631885859803942
